### ISSUE TITLE
Where is Encrypter.exe & Junk Gen?

### ISSUE THREAD

**Issue by WardPearce** [ThaisenPM/Loader3#10]
Hey,
Where are we meant to find the Encrypter & Junk Gen software? 

From my understanding it's something we need to purchase off you?

**Comment by WardPearce** [comment]
From my understanding it's something we need to purchase off you?

**Comment by JohnnyZer0** [comment]
ye, im confused too

**Comment by ThaisenPM** [comment]
They're not included
