### ISSUE TITLE
Always says password is incorrect

### ISSUE THREAD

**Issue by M1XT3NZ** [ThaisenPM/Loader3#12]
Yes i did change the mysql login and double checked everything...

**Comment by lizenoon** [comment]
I have this issue also

**Comment by bogdaNNNN1** [comment]
You need just to learn a little bit of programming, or have a brain actually to check the files. Something is wrong with password messages on webpage and you need to change it in the loader either change it in the web file to be the same.
I don't like spoonfeeding so I will not help you 😢

**Comment by ThaisenPM** [comment]
Your SQL login info is incorrect

**Comment by robowarrior88** [comment]
Your brain in incorrect. THE LOGIN IS CORRECT IDIOT!
Ofcourse you don't know because you know it's not working!
