### ISSUE TITLE
File Encrypter.exe?

### ISSUE THREAD

**Issue by TheHatMan98** [ThaisenPM/Loader3#3]
File Encrypter.exe? where can i find it?

**Comment by SimDoes** [comment]
its in https://github.com/ThaisenPM/Loader4
the source is different tho

**Comment by SurprisedBH** [comment]
404 where the fuck is file encrypter

**Comment by ThaisenPM** [comment]
@SimDoes That's a different encryption method + now a private repo

I don't give it out
