### ISSUE TITLE
Password incorrect

### ISSUE THREAD

**Issue by psxsahan** [ThaisenPM/Loader3#5]
Password incorrect MYBB ok its fixed

**Comment by psxsahan** [comment]
fixed it, php problem. Now i cant download Dll why?  WebClient Error Form3

**Comment by psxsahan** [comment]
Now gives Error : Please Enter a key. How can i do?

**Comment by psxsahan** [comment]
And how can i edit Form3

**Comment by Brodys** [comment]
@ThaisenPM I'm getting this issue where password is incorrect, but if i copy the link with my login info and my hardware id in my "mybb_users" it says h1 which should show form3, but when i login with the software it says password incorrect
